config/routes.rb
Rails.application.routes.draw do
  # get 'application/demo'
  # get 'application/index'
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  resources :payments
  resources :pockets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/pocket.rb
class Pocket < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def new
    @exam= Exam.new
  end

  def create
    exam= Exam.new(resource_params)
    exam.save
    flash[:notice] = 'Selamat mengerjakan!'
    redirect_to exams_path
  end

  def edit
    @exam = Exam.find(params[:id])
  end

  def update
    id = params[:id]
    @exam = Exam.find(id)
    @exam.update(resource_params)
    redirect_to exams_path
  end

  def destroy
    id = params[:id]
    @exam = Exam.find(id)
    @exam.destroy
    flash[:notice] = 'Semangat terus!'
    redirect_to exams_path
  end

  def index
    @exams = Exam.all
  end

  def show
    id = params[:id]
    @exam = Exam.find(id)
  end

  def resource_params
    params.require(:exam).permit(:title, :mapel, :duration, :nilai, :status, :label, :student_id)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end
end

app/controllers/pockets_controller.rb
class PocketsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/pockets_helper.rb
module PocketsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/exams/edit.html.erb
<%= form_for(@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>

    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :label %> </br>
    <%= f.text_field :label %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    <%= f.submit "Save" %>
<% end %>

app/views/exams/index.html.erb
<% if flash[:notice].present? %>
<% flash[:notice] %>
<% end %> </br>
<table>
<tr>
    <td>Title</td>
    <td>Mapel</td>
    <td>Duration</td>
    <td>Nilai</td>
    <td>Status</td>
    <td>Label</td>
    <td>Student_id</td>
</tr>
<% @exams.each do |exam| %>
    </tr>
<td><%= exam.title %></td>
<td><%= exam.mapel %></td>
<td><%= exam.duration %></td>
<td><%= exam.nilai %></td>
<td><%= exam.status %></td>
<td><%= exam.label %></td>
<td><%= exam.student_id %></td>
<td><%= link_to 'klik di sini', exam_path(exam) %> | <%= link_to 'Edit', edit_exam_path(exam.id) %> | <%= link_to 'Delete', exam_path(exam.id) ,method: :delete, data: {confirm: 'Yakin mau dihapus?'} %></td>
</tr>
<% end %>
</table>

<%= link_to 'New Exam', new_exam_path %>

app/views/exams/new.html.erb
<%= form_for(@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>

    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>

    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>

    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai %> </br>

    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>

    <%= f.label :label %> </br>
    <%= f.text_field :label %> </br>

    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>

    <%= f.submit "Save" %>
<% end %>

app/views/exams/show.html.erb
<% if flash[:notice].present? %>
<% flash[:notice] %>
<% end %> </br>
Title : <%= @exam.title %> </br>
Mapel : <%= @exam.mapel %> </br>
Duration : <%= @exam.duration %> </br>
Nilai : <%= @exam.nilai %> </br>
Status : <%= @exam.status %> </br>
Label : <%= @exam.label %> </br>
Student Id : <%= @exam.student_id %> </br>

app/views/payments/edit.html.erb
<h1>Payments#edit</h1>
<p>Find me in app/views/payments/edit.html.erb</p>

app/views/payments/index.html.erb
<h1>Payments#index</h1>
<p>Find me in app/views/payments/index.html.erb</p>

app/views/payments/new.html.erb
<h1>Payments#new</h1>
<p>Find me in app/views/payments/new.html.erb</p>

app/views/payments/show.html.erb
<h1>Payments#show</h1>
<p>Find me in app/views/payments/show.html.erb</p>

app/views/pockets/edit.html.erb
<h1>Pockets#edit</h1>
<p>Find me in app/views/pockets/edit.html.erb</p>

app/views/pockets/index.html.erb
<h1>Pockets#index</h1>
<p>Find me in app/views/pockets/index.html.erb</p>

app/views/pockets/new.html.erb
<h1>Pockets#new</h1>
<p>Find me in app/views/pockets/new.html.erb</p>

app/views/pockets/show.html.erb
<h1>Pockets#show</h1>
<p>Find me in app/views/pockets/show.html.erb</p>

app/views/reports/edit.html.erb
<h1>Reports#edit</h1>
<p>Find me in app/views/reports/edit.html.erb</p>

app/views/reports/index.html.erb
<h1>Reports#index</h1>
<p>Find me in app/views/reports/index.html.erb</p>

app/views/reports/new.html.erb
<h1>Reports#new</h1>
<p>Find me in app/views/reports/new.html.erb</p>

app/views/reports/show.html.erb
<h1>Reports#show</h1>
<p>Find me in app/views/reports/show.html.erb</p>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>

app/views/students/new.html.erb
<h1>Students#new</h1>
<p>Find me in app/views/students/new.html.erb</p>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>

app/views/teachers/edit.html.erb
<h1>Teachers#edit</h1>
<p>Find me in app/views/teachers/edit.html.erb</p>

app/views/teachers/index.html.erb
<h1>Teachers#index</h1>
<p>Find me in app/views/teachers/index.html.erb</p>

app/views/teachers/new.html.erb
<h1>Teachers#new</h1>
<p>Find me in app/views/teachers/new.html.erb</p>

app/views/teachers/show.html.erb
<h1>Teachers#show</h1>
<p>Find me in app/views/teachers/show.html.erb</p>